/* namespaced madules */
module Form = SimpleForm_Form;
module Submit = SimpleForm_Submit;
module TextInput = SimpleForm_TextInput;
module IntInput = SimpleForm_IntInput;
module FloatInput = SimpleForm_FloatInput;
module TextArea = SimpleForm_TextArea;
module Radio = SimpleForm_Radio;
module Checkbox = SimpleForm_Checkbox;
module Select = SimpleForm_Select;